apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tasky
  replicas: 2
  template:
    metadata:
        labels:
          app.kubernetes.io/name: tasky
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
        - name: tasky
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 100Mi
          image: '207567792559.dkr.ecr.us-east-1.amazonaws.com/tasky:latest'
          ports:
          - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: 'MONGODB_URI'