apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: tasky